### PR TITLE
[dev] Bug AB#59185 [Mobile][My Ministries > Serving Opps] After adding a new Opportunity in My Ministry, the "Actions" pop out drawer does not close automatically | Extend Mobile Action Bar Actions Button and Actions Drawer to provide the option of toggling the Actions Drawer closed when an option is clicked

### PR DESCRIPTION
**Pull request by cletux87**
See: https://github.com/saddlebackdev/church-management/pull/5874#discussion_r797350027
This is the React CM UI change required for "Solution 2".

### CODE REVIEW

**Review by groberts314 — APPROVED** [review]
LGTM

**Review by cbrewer1689 — APPROVED** [review]
Looks good.

**Comment by cbrewer1689** [comment]
Why `do not merge` @cletux87 ?

**Comment by groberts314** [comment]
> Why `do not merge` @cletux87 ?

@cbrewer1689 I think due to discussion here: https://github.com/saddlebackdev/church-management/pull/5874#discussion_r797350027

**Review by fantaJinMode — APPROVED** [review]
LGTM 👍

**Review by groberts314 — APPROVED** [review]
LGTM

**Pull request merged**
