### PR TITLE
Task [10087] Immersive nav (Tier 3) -- part of PBI [8769] Serving Opportunities 1.1

### PR DESCRIPTION
**Pull request by gbulatov**
* Adds an option for a drawer to open from a left side (also support second wing and other drawer features)
* Updates documentation

### CODE REVIEW

**Comment by gbulatov** [comment]
@morethanfire @groberts314 Please have a look, we need this for tier 3 navigation in SO 1.1

**Comment by morethanfire** [comment]
I am struggling with the the term `side` vs `position`. For example in the **Rail** component we use position. I'd like to be consistent with the term we use. Are you opposed to updating the update to use `position`?

**Comment by IlyaRadinsky** [comment]
OK, will do tomorrow

**Comment by morethanfire** [comment]
Thanks!

**Comment by morethanfire** [comment]
👍 
Love it! I will merge this and kick out a release today.

**Pull request merged**
