### PR TITLE
Added light font for source sans sarif

### PR DESCRIPTION
**Pull request by bittu1028**

### CODE REVIEW

**Comment by groberts314** [comment]
Please forgive my ignorance ... but what we're doing here is making a couple of additional font weight variations available?  Seems okay to me.  Seems additive, which is generally safe.  @morethanfire ... any objections?

**Comment by groberts314** [comment]
@morethanfire Ping! :-)
@bittu1028 Can you advise on what feature (Backlog Item, Bug etc.) this affects, and the urgency?

**Comment by bittu1028** [comment]
@groberts314 I need the light font in the title of quick notification drawer which was posted as a bug by James in sketch cloud.

**Comment by groberts314** [comment]
@bittu1028 Let's linger on this during the 10:00 AM scrum with @morethanfire and James and such to see if this many font weight variations are really needed.

**Comment by groberts314** [comment]
Per the linger ... drumroll please ... :shipit: 🎉 
(Was hoping that if we _did_ end up shipping this it rolled with `1.18.6` but this will have to go into `1.18.7` I suppose ... sigh)

**Pull request merged**
