### PR TITLE
[dev] Bug AB#57694: [Person Record] Flags are not displayed on the drop down menu in the Phone Number field on Person Record 1.0

### PR DESCRIPTION
**Pull request by IamNotHuman**
Pulling assets from flag-icon-css github repo because the other repo was deleted. Tried to update the library to version 3 but it was too big of a effort and documentation provided easier option

### CODE REVIEW

**Review by groberts314 — APPROVED** [review]
This looks like a simple enough change.  Do we need to be aware of how the image assets are imported/exported, what path they live at, etc.?  Can we also clean up the image path on the church-management side once we get the new cut of React CM UI?

**Comment by groberts314** [comment]
Important Note to other reviewers (esp. @cbrewer1689 )
We are currently targeting this fix for [Bug AB#57694](https://dev.azure.com/saddlebackchurch/Church%20Management/_workitems/edit/57694) for 1.40.1 (patch release for Wed 2021-11-10, `church-management` branch `hotfix/1.40.1`).

**Review by raoufr — APPROVED** [review]

**Comment by raoufr** [comment]
Looking good to me. @IamNotHuman please address @groberts314's comments above when you get a chance, before we merge. I placed a `do not merge` label pending your response. Thanks much.

**Comment by IamNotHuman** [comment]
> This looks like a simple enough change. Do we need to be aware of how the image assets are imported/exported, what path they live at, etc.? Can we also clean up the image path on the church-management side once we get the new cut of React CM UI?



> This looks like a simple enough change. Do we need to be aware of how the image assets are imported/exported, what path they live at, etc.? Can we also clean up the image path on the church-management side once we get the new cut of React CM UI?

Library has a module that connects with this repo. https://github.com/lipis/flag-icons/tree/main/flags, looks like the specific version we use was connected to a deprecated repo by default.

**Comment by groberts314** [comment]
@raoufr I don't think there is a need for **`do not merge`** on this one.  I think this is ready to go.  If we have some issues exporting the images we can do a follow up PR, but I think let's let this one roll and get the updated React CM UI package published, and then get this integrated in `church-management`.

**Comment by groberts314** [comment]
@cbrewer1689 Do we think it's safe to upgrade from 10.2.3 to 10.2.4 in `hotfix/1.40.1` in `church-management`?
It would be this PR plus the changes already merged: https://github.com/saddlebackdev/react-cm-ui/compare/10.2.3...dev
* Remove 'Droid Serif' font
* Sectional Nav Tabs fix
* Fix hard-coded `type="user"` on `<Image>`

**Comment by cbrewer1689** [comment]
I think we need a 10.2.4 (1.40.1), 10.2.5 (1.41.0), and a 10.3.0 (10.42.0). 10.3.0 will include the sectional tabs update, timeline and maybe a couple other things.

**Review by cbrewer1689 — APPROVED** [review]

**Pull request merged**
