### PR TITLE
[dev] NoPBI Fixes the crash on DataGridTableRow render

### PR DESCRIPTION
**Pull request by IlyaRadinsky**
@morethanfire please have a look

### CODE REVIEW

**Comment by groberts314** [comment]
@IlyaRadinsky Let's please retire the gublatov fork in this repo as well and just use feature branches.

**Comment by IlyaRadinsky** [comment]
@groberts314 I've tried, but have no access to create branches in react-cm-ui repo.

**Comment by groberts314** [comment]
@IlyaRadinsky I'll see if I can rectify that.

**Comment by groberts314** [comment]
@IlyaRadinsky You should have write access to this repository now.

**Pull request merged**
