### PR TITLE
[dev] AB#96217 -- Ability to set an Audio Step's CTA

### PR DESCRIPTION
**Pull request by IamNotHuman**
added forward10, back10, pause icons

### CODE REVIEW

**Review by groberts314 — CHANGES_REQUESTED** [review]
Please add the new Icons to one of the categories on the UI Docs Page for Icons: https://github.com/saddlebackdev/react-cm-ui/blob/dev/docs/src/dataDisplay/icon/icon.jsx#L39-L305 (probably the "Actions" category).

That way they will show up on the [Icons page](https://cm-ui-docs.saddleback.com/components/data-display/icon).

**Comment by raoufr** [comment]
@IamNotHuman please address @groberts314's comment above when you get a chance. Thank you.

**Review by raoufr — APPROVED** [review]
Looking good to me provided @groberts314's comment is addressed

**Review by groberts314 — CHANGES_REQUESTED** [review]
Can we double check?  The 'back 10' and 'forward 10' icons look the same!

image

**Comment by groberts314** [comment]
@IamNotHuman Can you please run the docs site locally ( go to `/docs` folder, do `npm install` if you've never done it there, and then `npm start` and it runs on `http://localhost:8082`).  Please go to Icons page and verify the icons look correct, and post a screenshot.

**Comment by IamNotHuman** [comment]
> @IamNotHuman Can you please run the docs site locally ( go to `/docs` folder, do `npm install` if you've never done it there, and then `npm start` and it runs on `http://localhost:8082`). Please go to Icons page and verify the icons look correct, and post a screenshot.

Got it! 
image

**Review by groberts314 — APPROVED** [review]

**Comment by groberts314** [comment]
:shipit: as soon as current validation build passes.

**Pull request merged**
