### PR TITLE
[dev] [No Bug/PBI] Try to fix build issues with `node-gyp` package

### PR DESCRIPTION
**Pull request by groberts314**
See https://dev.azure.com/saddlebackchurch/Church%20Management/_build/results?buildId=26830&view=logs&j=db40ead0-d549-5fb8-3f02-9e9562a5d19f&t=e130dc5c-1eba-592f-1f04-e10b43691bdb

Adopted suggestion from here:
https://github.com/dlmanning/gulp-sass/issues/780#issuecomment-723098248

### CODE REVIEW

**Review by cbrewer1689 — APPROVED** [review]
👍

**Review by War777 — APPROVED** [review]
LGTM! Thanks @groberts314

**Comment by groberts314** [comment]
@War777 could you pull this branch, completely blow away `node_modules` in both root project and `docs` project, and then re-install and verify everything works okay?  If you don't have time, understood.  I just wanna make sure this dependency chain will work for various folks locally on various OSs, versions of node, etc.

**Comment by cbrewer1689** [comment]
@groberts314, I am not having any issues with installing node_modules after `rm -rf node_modules`. I think this PR is good.

**Comment by groberts314** [comment]
Wanna :shipit: ?
Then update your other branch and see if that build goes green, then ship that.

**Comment by War777** [comment]
> @War777 could you pull this branch, completely blow away `node_modules` in both root project and `docs` project, and then re-install and verify everything works okay? If you don't have time, understood. I just wanna make sure this dependency chain will work for various folks locally on various OSs, versions of node, etc.

Testing! One minute, please

**Comment by groberts314** [comment]
Copy that @War777  ... countdown hold! 😁

**Comment by War777** [comment]
I reinstalled everything and It works correctly as far as I can see :D

**Comment by groberts314** [comment]
Thanks @War777 

So ... gentlemen ... :shipit: ?

**Pull request merged**
