### PR TITLE
[dev] AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)

### PR DESCRIPTION
**Pull request by cbrewer1689**
This fixes warning messages we are getting from MUI about ContentProps.

### CODE REVIEW

**Review by groberts314 — APPROVED** [review]
LGTM

**Comment by cbrewer1689** [comment]
Sorry, apparently this is a work in progress. I removed them from the docs, but still have them in HC.

**Comment by cbrewer1689** [comment]
64e419b fixes the remaining issues.

**Review by fantaJinMode — APPROVED** [review]
LGTM 👍

**Pull request merged**
