### PR TITLE
[dev] No AB - Popover Fix and Table Header Styling Fix

### PR DESCRIPTION
**Pull request by cbrewer1689**

### CODE REVIEW

**Review by groberts314 — APPROVED** [review]
LGTM

**Comment by groberts314** [comment]
Azure DevOps is showing 1 failed unit test, but it's not clear from the output which one:
https://dev.azure.com/saddlebackchurch/Church%20Management/_build/results?buildId=26316&view=logs&j=92a4755a-6173-591e-5c07-8dbe1165e937&t=ce5ce15a-a386-5452-420b-bccb6f75f6dc&l=600

Do they all pass locally for you?

**Comment by groberts314** [comment]
I think I found the failing test (man it was _hard_):
```
  ● <PersonPanel /> › Should toggle Popover open and close onClick.

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      146 |         wrapper.setProps({});
      147 | 
    > 148 |         expect(props.onClickAway).toHaveBeenCalledTimes(1);
          |                                   ^
      149 |         expect(wrapper.find(`.${bemPopperName}`).first().prop('open')).toBe(false);
      150 |     });
      151 | 

      at Object.<anonymous> (src/dataDisplay/popover/__test__/popover.test.js:148:35)
```

**Comment by cbrewer1689** [comment]
Just push the fix.

**Comment by groberts314** [comment]
Yep, seems to be good now.  You wanna :shipit: or are you awaiting further review?

**Pull request merged**
